#!/usr/bin/env python3
"""Log work events into an Obsidian vault as Markdown."""

import argparse
import csv
import os
import re
import shutil
import subprocess
import sys
from collections import Counter, defaultdict
from datetime import datetime, timedelta

# ---- constants & regexes ---------------------------------------------------

VALID_TYPES = (
    "commit",
    "pull_request",
    "assignment",
    "lecture",
    "slides",
    "application",
    "resume",
    "study",
    "leetcode",
    "design",
    "interview",
)

SUBCOMMANDS = ("track", "today", "undo", "stats", "dash", "sync", "review", "label")

# Fields the writer owns; --x may not collide with them. `id` and `src` belong to
# sync: forging them by hand would break its dedupe and its audit trail.
RESERVED_FIELDS = ("type", "when", "detail", "topic", "duration", "id", "src")

# Job-application funnel, in order. Conversion is measured between neighbours.
PIPELINE_STAGES = ("applied", "oa", "phone", "onsite", "offer")

# A week with fewer logged days than this is reported as insufficient data,
# never as a decline.
MIN_LOGGED_DAYS = 3

# sync: one record per line, fields split by a byte no commit subject can contain.
GIT_FIELD_SEP = "\x1f"
GIT_LOG_FORMAT = GIT_FIELD_SEP.join(("%H", "%aI", "%s"))
SHORT_SHA_LEN = 8

# review: the reviewed week plus this many weeks of context in the table.
REVIEW_CONTEXT_WEEKS = 4
REVIEW_PROMPTS = ("What worked", "What slipped", "One change next week")

# Bars in the generated notes. Fixed width so one big week cannot stretch the table,
# and ASCII so the file stays readable in any editor, console or codepage.
BAR_WIDTH = 20
BAR_CHAR = "#"

# Dashboard's computed study table covers the same window as its Dataview block.
DASHBOARD_TOPIC_DAYS = 30

GENERATED_HEADER = (
    "<!-- Generated by tracker.py. This file is overwritten on every `t dash` run; do not edit. -->\n"
)
GENERATED_NOTES = ("Stats.md", "Dashboard.md")

LOG_HEADING_RE = re.compile(r"^## Log[ \t]*\r?$", re.MULTILINE)
NEXT_H2_RE = re.compile(r"^## (?!#)", re.MULTILINE)
COMPLETED_TASK_RE = re.compile(r"^- \[x\]\s+(.*)$")
FIELD_RE = re.compile(r"(\w+)::\s*([^|]*)")
HEADING_LINE_RE = re.compile(r"^#{1,6} ")
DAILY_NAME_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})\.md$")
EXTRA_KEY_RE = re.compile(r"^\w+$")
# Only lines this tool wrote are eligible for undo.
TOOL_LINE_RE = re.compile(r"^- \[x\] type:: \S+ \| when:: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}")


# ---- small helpers ---------------------------------------------------------


def die(message):
    print(message, file=sys.stderr)
    sys.exit(1)


def vault_path():
    raw = os.environ.get("VAULT_PATH")
    if not raw:
        die("VAULT_PATH is not set.")
    if not os.path.isdir(raw):
        die("VAULT_PATH does not exist: %s" % raw)
    return os.path.abspath(raw)


def now_local():
    return datetime.now()


def working_date(now=None):
    # Working day ends at 04:00, so subtract 4h before taking the date.
    if now is None:
        now = now_local()
    return (now - timedelta(hours=4)).date()


def working_day_start(now=None):
    wd = working_date(now)
    return datetime(wd.year, wd.month, wd.day, 4, 0, 0)


def parse_iso_date(text):
    try:
        return datetime.strptime(text, "%Y-%m-%d").date()
    except ValueError:
        die("date must be YYYY-MM-DD, got %s" % text)


def week_start(day):
    return day - timedelta(days=day.weekday())


def newline_of(content):
    if "\r\n" in content:
        return "\r\n"
    return "\n"


def sanitize(text):
    return text.replace("\r", " ").replace("\n", " ").replace("|", " ").strip()


def read_text(path):
    with open(path, "r", encoding="utf-8", newline="") as f:
        return f.read()


def write_text(path, content):
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(content)


# ---- log-line format -------------------------------------------------------


def parse_extra(raw):
    """Parse one --x key=value into a sanitized (key, value) pair."""
    key, sep, value = raw.partition("=")
    key = key.strip()
    value = sanitize(value)
    if not sep or not key:
        die("--x expects key=value, got %s" % raw)
    if not EXTRA_KEY_RE.match(key):
        die("--x key must be letters, digits or underscore, got %s" % key)
    if key in RESERVED_FIELDS:
        die("--x key %s is reserved; use the dedicated flag" % key)
    if not value:
        die("--x value for %s is empty" % key)
    return key, value


def parse_extras(raw_list):
    extras = []
    seen = set()
    for raw in raw_list or ():
        key, value = parse_extra(raw)
        if key in seen:
            die("--x key %s given twice" % key)
        seen.add(key)
        extras.append((key, value))
    return extras


def format_log_line(event_type, when, detail, topic, duration, extras=None):
    parts = [
        "type:: %s" % event_type,
        "when:: %s" % when.strftime("%Y-%m-%dT%H:%M"),
    ]
    if detail:
        parts.append("detail:: %s" % detail)
    if topic:
        parts.append("topic:: %s" % sanitize(topic))
    if duration is not None:
        parts.append("duration:: %s" % duration)
    for key, value in extras or ():
        parts.append("%s:: %s" % (key, value))
    return "- [x] " + " | ".join(parts)


# ---- daily-note I/O --------------------------------------------------------


def end_of_last_nonempty_line(content, start, end):
    insert_at = start
    pos = start
    while pos < end:
        nl_pos = content.find("\n", pos, end)
        if nl_pos == -1:
            line = content[pos:end].rstrip("\r")
            if line.strip():
                insert_at = end
            break
        line = content[pos:nl_pos].rstrip("\r")
        if line.strip():
            insert_at = nl_pos + 1
        pos = nl_pos + 1
    return insert_at


def insert_under_log(content, log_line):
    """Insert log_line under ## Log. Bytes before and after the insert point stay identical."""
    nl = newline_of(content) if content else "\n"
    addition = log_line + nl

    m = LOG_HEADING_RE.search(content)
    if not m:
        # Spec: append \n## Log\n at end, then the line.
        return content + "\n## Log\n" + log_line + "\n"

    after = m.end()
    if after < len(content) and content[after] == "\n":
        after += 1

    next_h2 = NEXT_H2_RE.search(content, after)
    body_end = next_h2.start() if next_h2 else len(content)
    insert_at = end_of_last_nonempty_line(content, after, body_end)

    if insert_at > 0 and content[insert_at - 1] != "\n":
        addition = nl + addition
    return content[:insert_at] + addition + content[insert_at:]


def daily_path(vault, day):
    return os.path.join(vault, "daily", "%s.md" % day.isoformat())


# ---- track / today / undo --------------------------------------------------


def cmd_track(args):
    event_type = args.event_type
    if event_type not in VALID_TYPES:
        die("unknown type %s; expected one of: %s" % (event_type, ", ".join(VALID_TYPES)))
    if (args.topic is not None or args.duration is not None) and event_type != "study":
        die("--topic and --duration are only valid with type study")

    extras = parse_extras(args.extra)
    vault = vault_path()
    when = now_local()
    if args.date:
        day = parse_iso_date(args.date)
    else:
        day = working_date(when)

    detail = sanitize(" ".join(args.detail)) if args.detail else ""
    log_line = format_log_line(event_type, when, detail, args.topic, args.duration, extras)

    path = daily_path(vault, day)

    if not os.path.exists(path):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        content = "# %s\n\n## Log\n%s\n" % (day.isoformat(), log_line)
        write_text(path, content)
        return

    content = read_text(path)
    write_text(path, insert_under_log(content, log_line))


def cmd_today(args):
    vault = vault_path()
    day = parse_iso_date(args.date) if args.date else working_date()
    path = daily_path(vault, day)
    print(day.isoformat())
    if not os.path.isfile(path):
        print("  (no note)")
        return
    lines = [ln.rstrip("\r") for ln in log_section(read_text(path)).splitlines()]
    lines = [ln for ln in lines if ln.strip()]
    if not lines:
        print("  (no events)")
        return
    for line in lines:
        print("  %s" % line)


def iter_line_spans(content, start, end):
    """Yield (line_start, line_end) offsets, line_end excluding the newline."""
    pos = start
    while pos < end:
        nl_pos = content.find("\n", pos, end)
        if nl_pos == -1:
            yield pos, end
            return
        yield pos, nl_pos
        pos = nl_pos + 1


def last_tool_line(content):
    """Return (line_start, cut_end, text) of the last tool-written log line, or None."""
    span = log_span(content)
    if span is None:
        return None
    found = None
    for line_start, line_end in iter_line_spans(content, span[0], span[1]):
        text = content[line_start:line_end].rstrip("\r")
        if TOOL_LINE_RE.match(text):
            cut_end = line_end + 1 if line_end < len(content) and content[line_end] == "\n" else line_end
            found = (line_start, cut_end, text)
    return found


def cmd_undo(args):
    vault = vault_path()
    day = parse_iso_date(args.date) if args.date else working_date()
    path = daily_path(vault, day)
    if not os.path.isfile(path):
        die("no daily note for %s" % day.isoformat())

    content = read_text(path)
    found = last_tool_line(content)
    if found is None:
        die("no tracker-written line to undo in %s" % day.isoformat())
    line_start, cut_end, text = found

    print("remove from %s:" % day.isoformat())
    print("  %s" % text)
    if not args.yes:
        if not sys.stdin.isatty():
            print("not a terminal; pass --yes to remove", file=sys.stderr)
            return
        try:
            reply = input("Remove? [y/N] ")
        except EOFError:
            return
        if reply.strip() != "y":
            return

    write_text(path, content[:line_start] + content[cut_end:])


# ---- event loading & parsing -----------------------------------------------
#
# Tolerant reader: anything that does not look like a tracker line is skipped, never
# fatal. The filename is authoritative for which day an event counts under.


def log_span(content):
    """Return (start, end) offsets of the body under ## Log, or None."""
    m = LOG_HEADING_RE.search(content)
    if not m:
        return None
    after = m.end()
    if after < len(content) and content[after] == "\n":
        after += 1
    next_h2 = NEXT_H2_RE.search(content, after)
    end = next_h2.start() if next_h2 else len(content)
    return after, end


def log_section(content):
    span = log_span(content)
    if span is None:
        return ""
    return content[span[0]:span[1]]


def parse_fields(rest):
    fields = {}
    for key, val in FIELD_RE.findall(rest):
        fields[key] = val.strip()
    return fields


def parse_when_field(value):
    try:
        return datetime.fromisoformat(value)
    except ValueError:
        return None


def parse_log_file(path, file_date):
    """Return (events, unparseable_count, mismatch_warnings). Counts go under file_date."""
    content = read_text(path)
    events = []
    unparseable = 0
    warnings = []
    for raw in log_section(content).splitlines():
        line = raw.rstrip("\r")
        m = COMPLETED_TASK_RE.match(line)
        if not m:
            continue
        fields = parse_fields(m.group(1))
        event_type = fields.get("type")
        if not event_type:
            unparseable += 1
            continue
        when_raw = fields.get("when")
        if when_raw:
            when_dt = parse_when_field(when_raw)
            if when_dt is not None:
                delta = abs((when_dt.date() - file_date).days)
                if delta > 1:
                    warnings.append(
                        "warning: %s: when:: %s differs from filename by more than one day"
                        % (os.path.basename(path), when_raw)
                    )
        events.append(fields)
    return events, unparseable, warnings


def iter_day_files(vault):
    """Yield (date, path) for every daily note, oldest first."""
    daily_dir = os.path.join(vault, "daily")
    if not os.path.isdir(daily_dir):
        return
    for name in sorted(os.listdir(daily_dir)):
        m = DAILY_NAME_RE.match(name)
        if not m:
            continue
        try:
            day = datetime.strptime(m.group(1), "%Y-%m-%d").date()
        except ValueError:
            continue
        yield day, os.path.join(daily_dir, name)


def load_events(vault, start=None, end=None, warn_start=None):
    """Return (events, unparseable) for daily notes in [start, end]. Filename is authoritative.

    Streaks need all of history, but complaining about notes outside the window the user
    asked to see is noise: warnings and the unparseable count cover days >= warn_start only.
    """
    events = []
    unparseable = 0
    for day, path in iter_day_files(vault):
        if start is not None and day < start:
            continue
        if end is not None and day > end:
            continue
        try:
            parsed, skipped, warnings = parse_log_file(path, day)
        except OSError:
            # A note we cannot read is a warning, never a crash of the read path.
            print("warning: could not read %s" % path, file=sys.stderr)
            continue
        if warn_start is not None and day >= warn_start:
            unparseable += skipped
            for msg in warnings:
                print(msg, file=sys.stderr)
        for fields in parsed:
            fields["_date"] = day
            events.append(fields)
    return events, unparseable


# ---- numbers engine --------------------------------------------------------


def event_minutes(fields):
    """Study duration in minutes, or None when absent/malformed."""
    try:
        return int((fields.get("duration") or "").strip())
    except ValueError:
        return None


def summarize(events):
    """Counts by type, study minutes by topic, and sessions missing a duration."""
    type_counts = Counter()
    study_minutes = Counter()
    sessions_without_duration = 0
    for fields in events:
        type_counts[fields["type"]] += 1
        if fields["type"] != "study":
            continue
        minutes = event_minutes(fields)
        if minutes is None:
            sessions_without_duration += 1
            continue
        study_minutes[fields.get("topic") or "(untagged)"] += minutes
    return type_counts, study_minutes, sessions_without_duration


def logged_days(events):
    return {fields["_date"] for fields in events}


def streak(days, today, upto=None):
    """(current, longest) run of consecutive days present in `days`."""
    if not days:
        return 0, 0
    ordered = sorted(days)
    longest = 1
    run = 1
    for prev, cur in zip(ordered, ordered[1:]):
        run = run + 1 if (cur - prev).days == 1 else 1
        longest = max(longest, run)

    # Today still counts as unbroken until it is over, so anchor on yesterday
    # when nothing is logged yet today.
    anchor = today if today in days else today - timedelta(days=1)
    current = 0
    while anchor in days:
        current += 1
        anchor -= timedelta(days=1)
    if upto is not None:
        current = min(current, upto)
    return current, longest


# ---- reports & tables ------------------------------------------------------


def render_table(headers, rows):
    widths = [len(h) for h in headers]
    for row in rows:
        for i, cell in enumerate(row):
            widths[i] = max(widths[i], len(cell))
    lines = ["  ".join(h.ljust(widths[i]) for i, h in enumerate(headers)).rstrip()]
    for row in rows:
        lines.append("  ".join(cell.ljust(widths[i]) for i, cell in enumerate(row)).rstrip())
    return lines


def weekly_buckets(events, weeks, today):
    """Newest-first list of per-week aggregates."""
    current_week = week_start(today)
    starts = [current_week - timedelta(weeks=i) for i in range(weeks)]
    by_week = defaultdict(list)
    for fields in events:
        by_week[week_start(fields["_date"])].append(fields)

    buckets = []
    for start in starts:
        bucket_events = by_week.get(start, [])
        counts, minutes, _missing = summarize(bucket_events)
        buckets.append(
            {
                "start": start,
                "events": bucket_events,
                "counts": counts,
                "total": len(bucket_events),
                "study_min": sum(minutes.values()),
                "days": len(logged_days(bucket_events)),
            }
        )
    return buckets


def trend_label(buckets, index):
    """Compare a week against the average of the four weeks before it."""
    bucket = buckets[index]
    if bucket["days"] < MIN_LOGGED_DAYS:
        return "low data"
    prior = [b for b in buckets[index + 1: index + 5] if b["days"] >= MIN_LOGGED_DAYS]
    if len(prior) < 2:
        return "n/a"
    avg = sum(b["total"] for b in prior) / len(prior)
    if avg == 0:
        return "n/a"
    pct = (bucket["total"] - avg) / avg * 100
    if abs(pct) < 5:
        return "flat"
    return "%+d%% vs 4wk" % round(pct)


def weekly_report(buckets):
    """Lines for the weekly table: one column per type seen, plus study minutes."""
    totals = Counter()
    for bucket in buckets:
        totals.update(bucket["counts"])
    types = [name for name, _ in totals.most_common()]

    headers = ["week", "days", "events"] + types + ["study_min", "trend"]
    rows = []
    for i, bucket in enumerate(buckets):
        row = [
            bucket["start"].isoformat(),
            str(bucket["days"]),
            str(bucket["total"]),
        ]
        row += [str(bucket["counts"].get(name, 0)) for name in types]
        row.append(str(bucket["study_min"]))
        row.append(trend_label(buckets, i))
        rows.append(row)
    return headers, rows


def difficulty_report(buckets):
    """Weekly leetcode counts by diff::, to catch an easy-only grind."""
    levels = []
    for bucket in buckets:
        for fields in bucket["events"]:
            if fields["type"] != "leetcode":
                continue
            level = fields.get("diff") or "(none)"
            if level not in levels:
                levels.append(level)
    if not levels:
        return None
    order = [lv for lv in ("easy", "medium", "hard") if lv in levels]
    order += [lv for lv in levels if lv not in order]

    headers = ["week"] + order
    rows = []
    for bucket in buckets:
        counts = Counter(
            (f.get("diff") or "(none)") for f in bucket["events"] if f["type"] == "leetcode"
        )
        rows.append([bucket["start"].isoformat()] + [str(counts.get(lv, 0)) for lv in order])
    return headers, rows


def pipeline_report(events):
    """Stage counts across all history, plus conversion between neighbouring stages."""
    counts = Counter()
    for fields in events:
        stage = fields.get("stage")
        if stage:
            counts[stage] += 1
    if not counts:
        return None
    order = [s for s in PIPELINE_STAGES if s in counts]
    order += sorted(s for s in counts if s not in PIPELINE_STAGES)

    rows = []
    for i, stage in enumerate(order):
        conv = ""
        if i > 0 and stage in PIPELINE_STAGES and order[i - 1] in PIPELINE_STAGES:
            prev = counts[order[i - 1]]
            if prev:
                conv = "%d%%" % round(counts[stage] / prev * 100)
        rows.append([stage, str(counts[stage]), conv])
    return ["stage", "count", "from prev"], rows


def streak_lines(events, today, tracked_types=("leetcode", "study")):
    lines = []
    current, longest = streak(logged_days(events), today)
    lines.append("  any event   current %s, longest %s" % (current, longest))
    for name in tracked_types:
        days = {f["_date"] for f in events if f["type"] == name}
        if not days:
            continue
        current, longest = streak(days, today)
        lines.append("  %-11s current %s, longest %s" % (name, current, longest))
    return lines


def print_lines(lines):
    for line in lines:
        print(line)


# ---- generated notes (Stats.md / Dashboard.md) -----------------------------


def stats_markdown():
    return (
        GENERATED_HEADER
        + "\n"
        "# Stats\n"
        "\n"
        "## Event counts (last 30 days)\n"
        "\n"
        "```dataview\n"
        "TABLE length(rows) AS Count\n"
        'FROM "daily"\n'
        "WHERE file.day >= date(today) - dur(30 days)\n"
        "FLATTEN file.tasks AS t\n"
        "WHERE t.completed\n"
        "GROUP BY t.type\n"
        "SORT Count DESC\n"
        "```\n"
        "\n"
        "## Study minutes by topic\n"
        "\n"
        "```dataview\n"
        "TABLE sum(rows.t.duration) AS Minutes\n"
        'FROM "daily"\n'
        "WHERE file.day >= date(today) - dur(30 days)\n"
        "FLATTEN file.tasks AS t\n"
        'WHERE t.completed AND t.type = "study"\n'
        "GROUP BY t.topic\n"
        "SORT Minutes DESC\n"
        "```\n"
    )


def bar(value, peak, width=BAR_WIDTH):
    """A proportional ASCII bar. Any non-zero value gets at least one mark, so a
    small week reads as small, never as nothing."""
    if value <= 0 or peak <= 0:
        return ""
    return BAR_CHAR * max(1, int(round(value / peak * width)))


def bar_column(headers, rows, source_index, label="chart"):
    """Append a bar column scaled to the largest value in an existing numeric column."""
    values = []
    for row in rows:
        try:
            values.append(int(row[source_index]))
        except ValueError:
            values.append(0)
    peak = max(values) if values else 0
    return headers + [label], [row + [bar(v, peak)] for row, v in zip(rows, values)]


def study_topic_report(events):
    """Study minutes per topic, largest first, with a bar."""
    _counts, minutes, _missing = summarize(events)
    if not minutes:
        return None
    peak = max(minutes.values())
    rows = [[topic, str(mins), bar(mins, peak)] for topic, mins in minutes.most_common()]
    return ["topic", "minutes", "chart"], rows


def markdown_table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for row in rows:
        out.append("| " + " | ".join(row) + " |")
    return out


def dashboard_markdown(events, buckets, today):
    lines = [GENERATED_HEADER.rstrip("\n"), "", "# Dashboard", "", "Generated %s." % today.isoformat(), ""]

    lines += ["## Weekly", ""]
    headers, rows = weekly_report(buckets)
    # The bar tracks total events (column 2) — the number the trend column judges.
    lines += markdown_table(*bar_column(headers, rows, 2))
    lines.append("")
    lines.append(
        "`days` is days-with-at-least-one-event; a week under %s logged days reads as "
        "insufficient data, not decline." % MIN_LOGGED_DAYS
    )
    lines.append("")

    diff = difficulty_report(buckets)
    if diff:
        lines += ["## Leetcode difficulty mix", ""]
        lines += markdown_table(diff[0], diff[1])
        lines.append("")

    lines += ["## Streaks", ""]
    for line in streak_lines(events, today):
        lines.append("- " + line.strip())
    lines.append("")

    pipeline = pipeline_report(events)
    if pipeline:
        lines += ["## Application pipeline", ""]
        lines += markdown_table(pipeline[0], pipeline[1])
        lines.append("")

    lines += ["## Study minutes by topic (last %d days)" % DASHBOARD_TOPIC_DAYS, ""]
    window_start = today - timedelta(days=DASHBOARD_TOPIC_DAYS - 1)
    topics = study_topic_report(
        [f for f in events if window_start <= f["_date"] <= today]
    )
    if topics:
        lines += markdown_table(*topics)
        lines.append("")
    lines += [
        "```dataview",
        "TABLE sum(rows.t.duration) AS Minutes",
        'FROM "daily"',
        "WHERE file.day >= date(today) - dur(30 days)",
        "FLATTEN file.tasks AS t",
        'WHERE t.completed AND t.type = "study"',
        "GROUP BY t.topic",
        "SORT Minutes DESC",
        "```",
        "",
    ]
    return "\n".join(lines)


def emit_csv(events):
    base = ["date", "type", "when", "detail", "topic", "duration"]
    extra = sorted({k for f in events for k in f if k not in base and not k.startswith("_")})
    writer = csv.writer(sys.stdout, lineterminator="\n")
    writer.writerow(base + extra)
    for fields in events:
        row = [fields["_date"].isoformat()]
        row += [fields.get(name, "") for name in base[1:]]
        row += [fields.get(name, "") for name in extra]
        writer.writerow(row)


# ---- stats -----------------------------------------------------------------


def cmd_stats(args):
    if args.days not in ("7", "30"):
        die("days must be 7 or 30")
    if args.weeks is not None and args.weeks < 1:
        die("--weeks must be at least 1")

    vault = vault_path()
    today = working_date()

    if args.csv:
        events, _unparseable = load_events(vault)
        emit_csv(events)
        return

    weeks = args.weeks if args.weeks is not None else 8
    if args.weeks is not None:
        report_start = week_start(today) - timedelta(weeks=weeks - 1)
    else:
        report_start = today - timedelta(days=int(args.days) - 1)

    all_events, unparseable = load_events(vault, warn_start=report_start)

    if args.pipeline:
        report = pipeline_report(all_events)
        if report is None:
            print("no events with a stage:: field")
            return
        print_lines(render_table(report[0], report[1]))
        return

    week_window = week_start(today) - timedelta(weeks=weeks - 1)
    buckets = weekly_buckets(
        [f for f in all_events if f["_date"] >= week_window], weeks, today
    )

    if args.weeks is not None:
        headers, rows = weekly_report(buckets)
        print_lines(render_table(headers, rows))
        diff = difficulty_report(buckets)
        if diff:
            print("")
            print("leetcode by difficulty")
            print_lines(render_table(diff[0], diff[1]))
    else:
        n = int(args.days)
        window = [f for f in all_events if report_start <= f["_date"] <= today]
        type_counts, study_minutes, missing_duration = summarize(window)

        print("events (%s days)" % n)
        if type_counts:
            for name, count in type_counts.most_common():
                print("  %s  %s" % (name, count))
        else:
            print("  (none)")

        print("study minutes")
        if study_minutes:
            for name, mins in study_minutes.most_common():
                print("  %s  %s" % (name, mins))
        else:
            print("  (none)")
        if missing_duration:
            print("  sessions without duration: %s" % missing_duration)

        days = len(logged_days(window))
        print("logging: %s of %s days had an event" % (days, n))

    print("streaks")
    print_lines(streak_lines(all_events, today))

    if unparseable:
        print("skipped %s unparseable lines" % unparseable, file=sys.stderr)


# ---- dash ------------------------------------------------------------------
#
# The only command that overwrites files in the vault root. It is deliberately not
# folded into `stats`: "show me numbers" must never rewrite notes as a side effect.


def cmd_dash(args):
    if args.weeks < 1:
        die("--weeks must be at least 1")

    vault = vault_path()
    today = working_date()
    events, _unparseable = load_events(vault)

    window = week_start(today) - timedelta(weeks=args.weeks - 1)
    buckets = weekly_buckets([f for f in events if f["_date"] >= window], args.weeks, today)

    for name, body in (
        ("Stats.md", stats_markdown()),
        ("Dashboard.md", dashboard_markdown(events, buckets, today)),
    ):
        path = os.path.join(vault, name)
        write_text(path, body)
        print("wrote %s" % path)


# ---- sync ------------------------------------------------------------------
#
# Batch import of commits from local git. Not the write path in spirit: a failure just
# means "run it again later". The dedupe key `id::` lives in the Markdown like everything
# else, so re-running is always safe and there is no state file to drift.


def run_git(repo, argv):
    """Run a git command in repo. Returns stdout, or None on any failure."""
    exe = shutil.which("git")
    if not exe:
        return None
    try:
        proc = subprocess.run(
            [exe, "-C", repo] + argv,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
    except OSError:
        return None
    if proc.returncode != 0:
        return None
    return proc.stdout


def git_author_email(repo):
    """The repo's configured user.email — whose commits count as yours."""
    out = run_git(repo, ["config", "user.email"])
    return out.strip() if out else ""


def parse_git_date(text):
    """`%aI` is strict ISO 8601 with an offset; return it as local wall-clock time."""
    try:
        when = datetime.fromisoformat(text.strip())
    except ValueError:
        return None
    if when.tzinfo is not None:
        when = when.astimezone().replace(tzinfo=None)
    return when


def parse_git_log(text):
    """Parse GIT_LOG_FORMAT records into [{sha, when, subject}].

    Tolerant like every other reader here: a record missing fields or carrying an
    unreadable date is skipped, never fatal.
    """
    commits = []
    for raw in (text or "").splitlines():
        parts = raw.rstrip("\r").split(GIT_FIELD_SEP)
        if len(parts) != 3:
            continue
        sha, when_raw, subject = parts
        when = parse_git_date(when_raw)
        if not sha.strip() or when is None:
            continue
        commits.append({"sha": sha.strip(), "when": when, "subject": sanitize(subject)})
    return commits


def git_commits(repo, since, author):
    """Commits by `author` since `since`, or None if the repo could not be read."""
    argv = [
        "log",
        "--no-merges",
        "--since",
        since.isoformat(),
        "--pretty=format:" + GIT_LOG_FORMAT,
    ]
    if author:
        argv += ["--author", author]
    out = run_git(repo, argv)
    return None if out is None else parse_git_log(out)


def is_git_repo(path):
    return os.path.isdir(os.path.join(path, ".git"))


def discover_repos(root):
    """A --root directory plus its immediate subdirectories, keeping the git ones."""
    found = [root] if is_git_repo(root) else []
    try:
        names = sorted(os.listdir(root))
    except OSError:
        print("warning: cannot read --root %s" % root, file=sys.stderr)
        return found
    for name in names:
        path = os.path.join(root, name)
        if is_git_repo(path):
            found.append(path)
    return found


def resolve_repos(repos, roots):
    """Explicit flags win; TRACKER_REPOS is the zero-typing default."""
    paths = list(repos or ())
    for root in roots or ():
        paths += discover_repos(root)
    if not paths:
        raw = os.environ.get("TRACKER_REPOS", "")
        paths = [p for p in raw.split(os.pathsep) if p.strip()]

    # A repo reachable two ways must still be imported once.
    resolved, seen = [], set()
    for path in paths:
        full = os.path.abspath(os.path.expanduser(path.strip()))
        if full not in seen:
            seen.add(full)
            resolved.append(full)
    return resolved


def existing_ids(content):
    """The id:: values a note already carries — sync's dedupe key."""
    ids = set()
    for raw in log_section(content).splitlines():
        m = COMPLETED_TASK_RE.match(raw.rstrip("\r"))
        if not m:
            continue
        value = parse_fields(m.group(1)).get("id")
        if value:
            ids.add(value)
    return ids


def collect_commit_lines(repos, since, author):
    """Map working date -> [(when, id, log line)] for every commit worth appending."""
    by_day = defaultdict(list)
    scanned = 0
    for repo in repos:
        if not is_git_repo(repo):
            print("warning: not a git repository: %s" % repo, file=sys.stderr)
            continue
        who = author or git_author_email(repo)
        if not who:
            print(
                "warning: %s has no git user.email; pass --author" % repo, file=sys.stderr
            )
            continue
        commits = git_commits(repo, since, who)
        if commits is None:
            print("warning: could not read git log in %s" % repo, file=sys.stderr)
            continue
        scanned += 1
        name = sanitize(os.path.basename(repo)) or "repo"
        for commit in commits:
            short = commit["sha"][:SHORT_SHA_LEN]
            extras = [("repo", name), ("id", short), ("src", "sync")]
            line = format_log_line(
                "commit", commit["when"], commit["subject"], None, None, extras
            )
            by_day[working_date(commit["when"])].append((commit["when"], short, line))
    return by_day, scanned


def append_commit_lines(vault, by_day, dry_run):
    """Append the lines whose id the day's note does not already have. Returns (added, skipped)."""
    added = skipped = 0
    for day in sorted(by_day):
        path = daily_path(vault, day)
        content = read_text(path) if os.path.isfile(path) else None
        seen = existing_ids(content) if content is not None else set()

        fresh = []
        for _when, ident, line in sorted(by_day[day]):
            if ident in seen:
                skipped += 1
                continue
            seen.add(ident)
            fresh.append(line)
        if not fresh:
            continue

        added += len(fresh)
        if dry_run:
            print("%s  +%d" % (day.isoformat(), len(fresh)))
            for line in fresh:
                print("  %s" % line)
            continue

        if content is None:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            content = "# %s\n\n## Log\n" % day.isoformat()
        for line in fresh:
            content = insert_under_log(content, line)
        write_text(path, content)
    return added, skipped


def cmd_sync(args):
    if args.days < 1:
        die("--days must be at least 1")
    if not shutil.which("git"):
        die("git is not installed or not on PATH.")

    vault = vault_path()
    repos = resolve_repos(args.repo, args.root)
    if not repos:
        die("no repositories to sync; pass --repo/--root or set TRACKER_REPOS.")

    since = working_date() - timedelta(days=args.days)
    by_day, scanned = collect_commit_lines(repos, since, args.author)
    if not scanned:
        die("no repository could be read; nothing was written.")

    added, skipped = append_commit_lines(vault, by_day, args.dry_run)
    verb = "would add" if args.dry_run else "added"
    print(
        "%s %d event(s) from %d repo(s); %d already logged" % (verb, added, scanned, skipped)
    )


# ---- review ----------------------------------------------------------------
#
# Numbers only change behavior if you read them on a schedule. Unlike Stats.md and
# Dashboard.md, a review is written once and never regenerated: it holds your handwriting.


def review_week_start(today, week=None):
    """Monday of the week under review — last week by default, since you review on Sunday."""
    if week is not None:
        return week_start(week)
    return week_start(today) - timedelta(weeks=1)


def review_path(vault, start):
    year, week_no, _weekday = start.isocalendar()
    return os.path.join(vault, "reviews", "%04d-W%02d.md" % (year, week_no))


def review_markdown(events, start, today):
    """The week's numbers, pre-filled, followed by the three prompts."""
    end = start + timedelta(days=6)
    history = [f for f in events if f["_date"] <= end]
    window = [f for f in history if f["_date"] >= start - timedelta(weeks=REVIEW_CONTEXT_WEEKS)]
    buckets = weekly_buckets(window, REVIEW_CONTEXT_WEEKS + 1, end)

    year, week_no, _weekday = start.isocalendar()
    lines = [
        "# Review %04d-W%02d" % (year, week_no),
        "",
        # ASCII only: this string is printed to consoles whose codepage is not UTF-8.
        "%s to %s. Numbers generated %s; the prompts below are yours to answer."
        % (start.isoformat(), end.isoformat(), today.isoformat()),
        "",
        "## Numbers",
        "",
    ]
    headers, rows = weekly_report(buckets)
    lines += markdown_table(headers, rows)
    lines += ["", "Logged %d of 7 days." % buckets[0]["days"]]
    if buckets[0]["days"] < MIN_LOGGED_DAYS:
        lines.append(
            "Fewer than %d logged days: read this week as insufficient data, not decline."
            % MIN_LOGGED_DAYS
        )
    lines.append("")

    diff = difficulty_report(buckets)
    if diff:
        lines += ["## Leetcode difficulty mix", ""] + markdown_table(*diff) + [""]

    lines += ["## Streaks", ""]
    lines += ["- " + ln.strip() for ln in streak_lines(history, end)]
    lines.append("")

    pipeline = pipeline_report(history)
    if pipeline:
        lines += ["## Application pipeline", ""] + markdown_table(*pipeline) + [""]

    for prompt in REVIEW_PROMPTS:
        lines += ["## %s" % prompt, "", "- ", ""]
    return "\n".join(lines)


def cmd_review(args):
    vault = vault_path()
    today = working_date()
    start = review_week_start(today, parse_iso_date(args.week) if args.week else None)

    events, _unparseable = load_events(vault)
    body = review_markdown(events, start, today)

    if args.print_only:
        print(body)
        return

    path = review_path(vault, start)
    if os.path.exists(path):
        print("review already exists, leaving it alone: %s" % path)
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    write_text(path, body + "\n")
    print("wrote %s" % path)


# ---- label -----------------------------------------------------------------


def load_topics(vault):
    path = os.path.join(vault, "topics.txt")
    if not os.path.isfile(path):
        die("topics.txt not found in VAULT_PATH; create it with one topic per line.")
    topics = []
    for line in read_text(path).splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        topics.append(line)
    if not topics:
        die("topics.txt has no topics.")
    return topics


def iter_recent_notes(vault, since):
    since_ts = since.timestamp()
    for root, _dirs, files in os.walk(vault):
        for name in files:
            if not name.endswith(".md") or name in GENERATED_NOTES:
                continue
            path = os.path.join(root, name)
            try:
                mtime = os.path.getmtime(path)
            except OSError:
                continue
            if mtime < since_ts:
                continue
            yield path


def note_headings(content):
    if content.startswith("﻿"):
        content = content[1:]
    headings = []
    for raw in content.splitlines():
        line = raw.rstrip("\r")
        if HEADING_LINE_RE.match(line):
            headings.append(line)
    return headings


def build_label_prompt(title, headings, topics):
    # Single line: cmd.exe / claude.cmd drop everything after an embedded newline.
    heading_text = " | ".join(headings) if headings else "(no headings)"
    labels = ", ".join(topics)
    return (
        "Note title: %s. Headings: %s. Allowed labels: %s. "
        "Reply with exactly one label from this list, or the word other, and nothing else."
        % (title, heading_text, labels)
    )


def call_claude(prompt):
    exe = shutil.which("claude")
    if not exe:
        die("claude CLI is not installed or not on PATH.")
    argv = [exe, "-p", prompt]
    run_kw = {"capture_output": True, "text": True}
    # npm's claude.cmd is not a Win32 exe.
    if sys.platform == "win32" and exe.lower().endswith((".cmd", ".bat")):
        run_kw["shell"] = True
        argv = subprocess.list2cmdline(argv)
    try:
        proc = subprocess.run(argv, **run_kw)
    except OSError:
        die("claude CLI is not installed or not on PATH.")
    if proc.returncode != 0:
        err = (proc.stderr or proc.stdout or "claude CLI failed").strip()
        die(err.splitlines()[0] if err else "claude CLI failed.")
    return proc.stdout.strip()


def normalize_label(raw, topics):
    token = ""
    if raw.strip():
        token = raw.strip().splitlines()[0].strip()
    if token in topics or token == "other":
        return token, False
    return "other", True


def insert_topic_field(content, label):
    """Insert topic:: after the first heading (or at the top). Existing lines stay intact."""
    nl = newline_of(content) if content else "\n"
    field = "topic:: %s" % label
    bom = 1 if content.startswith("﻿") else 0
    body = content[bom:]
    m = re.search(r"^#{1,6} .*\r?$", body, re.MULTILINE)
    if not m:
        return content[:bom] + field + nl + content[bom:]
    after = bom + m.end()
    if after < len(content) and content[after] == "\n":
        after += 1
    addition = field + nl
    if after > 0 and content[after - 1] != "\n":
        addition = nl + addition
    return content[:after] + addition + content[after:]


def cmd_label(_args):
    vault = vault_path()
    topics = load_topics(vault)
    candidates = []
    for path in iter_recent_notes(vault, working_day_start()):
        content = read_text(path)
        if "topic::" in content:
            continue
        candidates.append((path, content))

    if not candidates:
        print("No notes to label.")
        return

    proposals = []
    for path, content in candidates:
        title = os.path.splitext(os.path.basename(path))[0]
        headings = note_headings(content)
        raw = call_claude(build_label_prompt(title, headings, topics))
        label, fallback = normalize_label(raw, topics)
        rel = os.path.relpath(path, vault)
        if fallback:
            shown = raw.strip().splitlines()[0].strip() if raw.strip() else ""
            print("warning: unexpected label %r for %s; using other" % (shown, rel), file=sys.stderr)
        proposals.append((path, content, label, rel))

    for _path, _content, label, rel in proposals:
        print("%s  %s" % (rel, label))

    if not sys.stdin.isatty():
        return
    try:
        reply = input("Apply? [y/N] ")
    except EOFError:
        return
    if reply.strip() != "y":
        return

    for path, content, label, _rel in proposals:
        write_text(path, insert_topic_field(content, label))


# ---- CLI -------------------------------------------------------------------


def build_parser():
    parser = argparse.ArgumentParser(prog="tracker.py")
    sub = parser.add_subparsers(dest="cmd", required=True)

    track_p = sub.add_parser("track", help="Append an event to the daily note")
    track_p.add_argument("event_type", metavar="type")
    track_p.add_argument("detail", nargs="*")
    track_p.add_argument("--date", metavar="D", help="Override working date (YYYY-MM-DD)")
    track_p.add_argument("--topic", metavar="T")
    track_p.add_argument("--duration", metavar="MIN", type=int)
    track_p.add_argument(
        "--x",
        dest="extra",
        action="append",
        metavar="K=V",
        help="Extra inline field; repeatable",
    )
    track_p.set_defaults(func=cmd_track)

    today_p = sub.add_parser("today", help="Print today's log lines")
    today_p.add_argument("--date", metavar="D", help="Show another date (YYYY-MM-DD)")
    today_p.set_defaults(func=cmd_today)

    undo_p = sub.add_parser("undo", help="Remove the last line this tool appended")
    undo_p.add_argument("--date", metavar="D", help="Undo on another date (YYYY-MM-DD)")
    undo_p.add_argument("--yes", action="store_true", help="Skip the confirmation prompt")
    undo_p.set_defaults(func=cmd_undo)

    stats_p = sub.add_parser("stats", help="Print event counts, streaks and trends")
    stats_p.add_argument("days", nargs="?", default="7")
    stats_p.add_argument("--weeks", metavar="N", type=int, help="Weekly buckets over N weeks")
    stats_p.add_argument("--pipeline", action="store_true", help="Application funnel by stage::")
    stats_p.add_argument("--csv", action="store_true", help="Dump all events as CSV to stdout")
    stats_p.set_defaults(func=cmd_stats)

    dash_p = sub.add_parser("dash", help="Write Stats.md and Dashboard.md into the vault")
    dash_p.add_argument(
        "--weeks", metavar="N", type=int, default=8, help="Weeks in the weekly table"
    )
    dash_p.set_defaults(func=cmd_dash)

    sync_p = sub.add_parser("sync", help="Import git commits into the daily notes")
    sync_p.add_argument(
        "--repo", action="append", metavar="PATH", help="Repository to scan; repeatable"
    )
    sync_p.add_argument(
        "--root",
        action="append",
        metavar="DIR",
        help="Scan DIR and its immediate subdirectories for repos; repeatable",
    )
    sync_p.add_argument("--days", metavar="N", type=int, default=14, help="Look back N days")
    sync_p.add_argument(
        "--author", metavar="EMAIL", help="Default: each repo's own git user.email"
    )
    sync_p.add_argument("--dry-run", action="store_true", help="Show what would be added")
    sync_p.set_defaults(func=cmd_sync)

    review_p = sub.add_parser("review", help="Write reviews/YYYY-Www.md for last week")
    review_p.add_argument("--week", metavar="D", help="Any date inside the week to review")
    review_p.add_argument(
        "--print", dest="print_only", action="store_true", help="Print instead of writing"
    )
    review_p.set_defaults(func=cmd_review)

    label_p = sub.add_parser("label", help="Suggest topic labels for recent notes")
    label_p.set_defaults(func=cmd_label)

    return parser


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv and not argv[0].startswith("-"):
        # `t commit "msg"` means `track commit "msg"`; subcommand names still win.
        if argv[0] in VALID_TYPES:
            argv.insert(0, "track")
        elif argv[0] not in SUBCOMMANDS:
            die(
                "unknown command or type %s; commands: %s; types: %s"
                % (argv[0], ", ".join(SUBCOMMANDS), ", ".join(VALID_TYPES))
            )
    parser = build_parser()
    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
