#!/usr/bin/env python3
"""Log work events into an Obsidian vault as Markdown."""

import argparse
import csv
import difflib
import os
import re
import stat
import sys
import tempfile
import textwrap
from collections import Counter, defaultdict
from datetime import datetime, timedelta

# ---- constants & regexes ---------------------------------------------------

VALID_TYPES = (
    "commit",
    "pull_request",
    "assignment",
    "lecture",
    "slides",
    "application",
    "resume",
    "study",
    "leetcode",
    "design",
    "interview",
    "merge",
    "assessment",
    "learning",
)

SUBCOMMANDS = (
    "track", "today", "undo", "stats", "week", "month", "dash", "sync", "review",
    "label", "suggest", "recap", "gui", "setup", "watch", "complete",
)

# `time` lines are written by `t watch` and reported separately from completed work.
TIME_TYPE = "time"

# `t week` is `t stats 7` under a name you actually reach for.
STATS_ALIASES = (("week", "7", "Last 7 days"), ("month", "30", "Last 30 days"))

# Fields the writer owns; --x may not collide with them. `id` and `src` belong to
# sync: forging them by hand would break its dedupe and its audit trail.
RESERVED_FIELDS = ("type", "when", "detail", "topic", "duration", "id", "src")

# Job-application funnel, in order. Conversion is measured between neighbours.
PIPELINE_STAGES = ("applied", "oa", "phone", "onsite", "offer")

# Below this coverage level, a weekly comparison is labeled low-data.
MIN_LOGGED_DAYS = 3

# Bars in the generated notes. Fixed width so one big week cannot stretch the table,
# and ASCII so the file stays readable in any editor, console or codepage.
BAR_WIDTH = 20
BAR_CHAR = "#"

# Dashboard's computed study table covers the same window as its Dataview block.
DASHBOARD_TOPIC_DAYS = 30
DASH_WEEKS = 8

GENERATED_HEADER = (
    "<!-- Generated by tracker.py. This file is overwritten on every `t dash` run; do not edit. -->\n"
)
GENERATED_NOTES = ("Stats.md", "Dashboard.md")

# Seed for a daily note the tool has to create, relative to the vault. Optional:
# without it the tool writes its own two-line skeleton.
DAILY_TEMPLATE = os.path.join("templates", "Daily.md")

LOG_HEADING_RE = re.compile(r"^## Log[ \t]*\r?$", re.MULTILINE)
NEXT_H2_RE = re.compile(r"^## (?!#)", re.MULTILINE)
COMPLETED_TASK_RE = re.compile(r"^- \[x\]\s+(.*)$")
FIELD_RE = re.compile(r"(\w+)::\s*([^|]*)")
DAILY_NAME_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})\.md$")
EXTRA_KEY_RE = re.compile(r"^\w+$")
# Only lines this tool wrote are eligible for undo.
TOOL_LINE_RE = re.compile(r"^- \[x\] type:: \S+ \| when:: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}")


# ---- small helpers ---------------------------------------------------------


def die(message):
    print(message, file=sys.stderr)
    sys.exit(1)


def suggest(word, options):
    """' did you mean X?' for a near miss, or '' when nothing is close enough."""
    close = difflib.get_close_matches(word.lower(), options, n=1, cutoff=0.6)
    return " Did you mean %s?" % close[0] if close else ""


def vault_path():
    raw = os.environ.get("VAULT_PATH")
    if not raw:
        die("VAULT_PATH is not set.")
    if not os.path.isdir(raw):
        die("VAULT_PATH does not exist: %s" % raw)
    return os.path.abspath(raw)


def now_local():
    return datetime.now()


def working_date(now=None):
    # Working day ends at 04:00, so subtract 4h before taking the date.
    if now is None:
        now = now_local()
    return (now - timedelta(hours=4)).date()


def working_day_start(now=None):
    wd = working_date(now)
    return datetime(wd.year, wd.month, wd.day, 4, 0, 0)


def parse_iso_date(text):
    try:
        return datetime.strptime(text, "%Y-%m-%d").date()
    except ValueError:
        die("date must be YYYY-MM-DD, got %s" % text)


def week_start(day):
    return day - timedelta(days=day.weekday())


def newline_of(content):
    if "\r\n" in content:
        return "\r\n"
    return "\n"


def sanitize(text):
    return text.replace("\r", " ").replace("\n", " ").replace("|", " ").strip()


def read_text(path):
    with open(path, "r", encoding="utf-8", newline="") as f:
        return f.read()


def write_text(path, content):
    """Atomically replace a text file, so interruption cannot leave it truncated."""
    directory = os.path.dirname(os.path.abspath(path)) or "."
    os.makedirs(directory, exist_ok=True)
    try:
        existing_mode = stat.S_IMODE(os.stat(path).st_mode)
    except OSError:
        existing_mode = None
    fd, temporary = tempfile.mkstemp(prefix=".%s." % os.path.basename(path), dir=directory)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        if existing_mode is not None:
            os.chmod(temporary, existing_mode)
        os.replace(temporary, path)
        temporary = None
        if os.name != "nt":
            # Persist the directory entry as well as the file contents on POSIX.
            try:
                directory_fd = os.open(directory, os.O_RDONLY)
                try:
                    os.fsync(directory_fd)
                finally:
                    os.close(directory_fd)
            except OSError:
                pass
    finally:
        if temporary is not None:
            try:
                os.unlink(temporary)
            except OSError:
                pass


def locked_note(path):
    return sibling_module("locking").note_lock(path)
# ---- log-line format -------------------------------------------------------


def parse_extra(raw):
    """Parse one --x key=value into a sanitized (key, value) pair."""
    key, sep, value = raw.partition("=")
    key = key.strip()
    value = sanitize(value)
    if not sep or not key:
        die("--x expects key=value, got %s" % raw)
    if not EXTRA_KEY_RE.match(key):
        die("--x key must be letters, digits or underscore, got %s" % key)
    if key in RESERVED_FIELDS:
        die("--x key %s is reserved; use the dedicated flag" % key)
    if not value:
        die("--x value for %s is empty" % key)
    return key, value


def parse_extras(raw_list):
    extras = []
    seen = set()
    for raw in raw_list or ():
        key, value = parse_extra(raw)
        if key in seen:
            die("--x key %s given twice" % key)
        seen.add(key)
        extras.append((key, value))
    return extras


def format_log_line(event_type, when, detail, topic, duration, extras=None):
    parts = [
        "type:: %s" % event_type,
        "when:: %s" % when.strftime("%Y-%m-%dT%H:%M"),
    ]
    if detail:
        parts.append("detail:: %s" % detail)
    if topic:
        parts.append("topic:: %s" % sanitize(topic))
    if duration is not None:
        parts.append("duration:: %s" % duration)
    for key, value in extras or ():
        parts.append("%s:: %s" % (key, value))
    return "- [x] " + " | ".join(parts)


# ---- daily-note I/O --------------------------------------------------------


def end_of_last_nonempty_line(content, start, end):
    insert_at = start
    pos = start
    while pos < end:
        nl_pos = content.find("\n", pos, end)
        if nl_pos == -1:
            line = content[pos:end].rstrip("\r")
            if line.strip():
                insert_at = end
            break
        line = content[pos:nl_pos].rstrip("\r")
        if line.strip():
            insert_at = nl_pos + 1
        pos = nl_pos + 1
    return insert_at


def insert_under_log(content, log_line):
    """Insert log_line under ## Log. Bytes before and after the insert point stay identical."""
    nl = newline_of(content) if content else "\n"
    addition = log_line + nl

    m = LOG_HEADING_RE.search(content)
    if not m:
        # Spec: append \n## Log\n at end, then the line.
        return content + "\n## Log\n" + log_line + "\n"

    after = m.end()
    if after < len(content) and content[after] == "\n":
        after += 1

    next_h2 = NEXT_H2_RE.search(content, after)
    body_end = next_h2.start() if next_h2 else len(content)
    insert_at = end_of_last_nonempty_line(content, after, body_end)

    if insert_at > 0 and content[insert_at - 1] != "\n":
        addition = nl + addition
    return content[:insert_at] + addition + content[insert_at:]


def daily_path(vault, day):
    return os.path.join(vault, "daily", "%s.md" % day.isoformat())


def new_daily_content(vault, day):
    """Seed text for a daily note that does not exist yet.

    A vault template wins if there is one, so a note created by the CLI looks like
    one created by Obsidian. `{{date}}` is Obsidian's own placeholder, so the same
    file serves both. An unreadable template is a warning, never a lost event.
    """
    path = os.path.join(vault, DAILY_TEMPLATE)
    if os.path.isfile(path):
        try:
            body = read_text(path).replace("{{date}}", day.isoformat())
        except OSError:
            print("warning: could not read %s" % path, file=sys.stderr)
        else:
            if body and not body.endswith("\n"):
                body += newline_of(body)
            return body
    return "# %s\n\n## Log\n" % day.isoformat()


# ---- track / today / undo --------------------------------------------------


def cmd_track(args):
    event_type = args.event_type
    if event_type not in VALID_TYPES:
        die(
            "unknown type %s.%s\nexpected one of: %s"
            % (event_type, suggest(event_type, VALID_TYPES), ", ".join(VALID_TYPES))
        )
    if (args.topic is not None or args.duration is not None) and event_type != "study":
        die("--topic and --duration are only valid with type study")

    extras = parse_extras(args.extra)
    vault = vault_path()
    when = now_local()
    if args.date:
        day = parse_iso_date(args.date)
    else:
        day = working_date(when)

    detail = sanitize(" ".join(args.detail)) if args.detail else ""
    log_line = format_log_line(event_type, when, detail, args.topic, args.duration, extras)

    path = daily_path(vault, day)

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with locked_note(path):
        content = read_text(path) if os.path.exists(path) else new_daily_content(vault, day)
        write_text(path, insert_under_log(content, log_line))


def cmd_today(args):
    """What is logged today. Events only: a note seeded from the template is mostly
    unticked boxes and comments, and none of that is something you did."""
    vault = vault_path()
    day = parse_iso_date(args.date) if args.date else working_date()
    path = daily_path(vault, day)
    print(day.isoformat())
    if not os.path.isfile(path):
        print("  (no note)")
        return

    events, waiting = [], 0
    for raw in log_section(read_text(path)).splitlines():
        line = raw.rstrip("\r").strip()
        if COMPLETED_TASK_RE.match(line):
            events.append(line)
        elif line.startswith("- [ ]"):
            waiting += 1

    if not events:
        print("  (no events)")
    for line in events:
        print("  %s" % line)
    if waiting:
        print("  (%d unticked box%s waiting)" % (waiting, "" if waiting == 1 else "es"))


def iter_line_spans(content, start, end):
    """Yield (line_start, line_end) offsets, line_end excluding the newline."""
    pos = start
    while pos < end:
        nl_pos = content.find("\n", pos, end)
        if nl_pos == -1:
            yield pos, end
            return
        yield pos, nl_pos
        pos = nl_pos + 1


def last_tool_line(content):
    """Return (line_start, cut_end, text) of the last tool-written log line, or None."""
    span = log_span(content)
    if span is None:
        return None
    found = None
    for line_start, line_end in iter_line_spans(content, span[0], span[1]):
        text = content[line_start:line_end].rstrip("\r")
        if TOOL_LINE_RE.match(text):
            cut_end = line_end + 1 if line_end < len(content) and content[line_end] == "\n" else line_end
            found = (line_start, cut_end, text)
    return found


def cmd_undo(args):
    vault = vault_path()
    day = parse_iso_date(args.date) if args.date else working_date()
    path = daily_path(vault, day)
    if not os.path.isfile(path):
        die("no daily note for %s" % day.isoformat())

    content = read_text(path)
    found = last_tool_line(content)
    if found is None:
        die("no tracker-written line to undo in %s" % day.isoformat())
    line_start, cut_end, text = found

    print("remove from %s:" % day.isoformat())
    print("  %s" % text)
    if not args.yes:
        if not sys.stdin.isatty():
            print("not a terminal; pass --yes to remove", file=sys.stderr)
            return
        try:
            reply = input("Remove? [y/N] ")
        except EOFError:
            return
        if reply.strip() != "y":
            return

    with locked_note(path):
        latest = read_text(path)
        latest_found = last_tool_line(latest)
        if latest_found is None or latest_found[2] != text:
            die("daily note changed while undo was waiting; run undo again")
        latest_start, latest_end, _latest_text = latest_found
        write_text(path, latest[:latest_start] + latest[latest_end:])


# ---- event loading & parsing -----------------------------------------------
#
# Tolerant reader: anything that does not look like a tracker line is skipped, never
# fatal. The filename is authoritative for which day an event counts under.


def log_span(content):
    """Return (start, end) offsets of the body under ## Log, or None."""
    m = LOG_HEADING_RE.search(content)
    if not m:
        return None
    after = m.end()
    if after < len(content) and content[after] == "\n":
        after += 1
    next_h2 = NEXT_H2_RE.search(content, after)
    end = next_h2.start() if next_h2 else len(content)
    return after, end


def log_section(content):
    span = log_span(content)
    if span is None:
        return ""
    return content[span[0]:span[1]]


def parse_fields(rest):
    fields = {}
    for key, val in FIELD_RE.findall(rest):
        fields[key] = val.strip()
    return fields


def parse_when_field(value):
    try:
        return datetime.fromisoformat(value)
    except ValueError:
        return None


def parse_log_file(path, file_date):
    """Return (events, unparseable_count, mismatch_warnings). Counts go under file_date."""
    content = read_text(path)
    events = []
    unparseable = 0
    warnings = []
    for raw in log_section(content).splitlines():
        line = raw.rstrip("\r")
        m = COMPLETED_TASK_RE.match(line)
        if not m:
            continue
        fields = parse_fields(m.group(1))
        event_type = fields.get("type")
        if not event_type:
            unparseable += 1
            continue
        when_raw = fields.get("when")
        if when_raw:
            when_dt = parse_when_field(when_raw)
            if when_dt is not None:
                delta = abs((when_dt.date() - file_date).days)
                if delta > 1:
                    warnings.append(
                        "warning: %s: when:: %s differs from filename by more than one day"
                        % (os.path.basename(path), when_raw)
                    )
        events.append(fields)
    return events, unparseable, warnings


def iter_day_files(vault):
    """Yield (date, path) for every daily note, oldest first."""
    daily_dir = os.path.join(vault, "daily")
    if not os.path.isdir(daily_dir):
        return
    for name in sorted(os.listdir(daily_dir)):
        m = DAILY_NAME_RE.match(name)
        if not m:
            continue
        try:
            day = datetime.strptime(m.group(1), "%Y-%m-%d").date()
        except ValueError:
            continue
        yield day, os.path.join(daily_dir, name)


def load_events(vault, start=None, end=None, warn_start=None):
    """Return (events, unparseable) for daily notes in [start, end]. Filename is authoritative.

    Streaks need all of history, but complaining about notes outside the window the user
    asked to see is noise: warnings and the unparseable count cover days >= warn_start only.
    """
    events = []
    unparseable = 0
    for day, path in iter_day_files(vault):
        if start is not None and day < start:
            continue
        if end is not None and day > end:
            continue
        try:
            parsed, skipped, warnings = parse_log_file(path, day)
        except OSError:
            # A note we cannot read is a warning, never a crash of the read path.
            print("warning: could not read %s" % path, file=sys.stderr)
            continue
        if warn_start is not None and day >= warn_start:
            unparseable += skipped
            for msg in warnings:
                print(msg, file=sys.stderr)
        for fields in parsed:
            fields["_date"] = day
            events.append(fields)
    return events, unparseable


# ---- numbers engine --------------------------------------------------------


def event_minutes(fields):
    """Study duration in minutes, or None when absent/malformed."""
    try:
        return int((fields.get("duration") or "").strip())
    except ValueError:
        return None


def summarize(events):
    """Counts by type, study minutes by topic, and sessions missing a duration."""
    type_counts = Counter()
    study_minutes = Counter()
    sessions_without_duration = 0
    for fields in events:
        if fields["type"] == TIME_TYPE:
            continue
        type_counts[fields["type"]] += 1
        if fields["type"] != "study":
            continue
        minutes = event_minutes(fields)
        if minutes is None:
            sessions_without_duration += 1
            continue
        study_minutes[fields.get("topic") or "(untagged)"] += minutes
    return type_counts, study_minutes, sessions_without_duration


def logged_days(events):
    return {f["_date"] for f in events if f["type"] != TIME_TYPE}


def streak(days, today, upto=None):
    """(current, longest) run of consecutive days present in `days`."""
    if not days:
        return 0, 0
    ordered = sorted(days)
    longest = 1
    run = 1
    for prev, cur in zip(ordered, ordered[1:]):
        run = run + 1 if (cur - prev).days == 1 else 1
        longest = max(longest, run)

    # Today still counts as unbroken until it is over, so anchor on yesterday
    # when nothing is logged yet today.
    anchor = today if today in days else today - timedelta(days=1)
    current = 0
    while anchor in days:
        current += 1
        anchor -= timedelta(days=1)
    if upto is not None:
        current = min(current, upto)
    return current, longest


# ---- reports & tables ------------------------------------------------------


def render_table(headers, rows):
    widths = [len(h) for h in headers]
    for row in rows:
        for i, cell in enumerate(row):
            widths[i] = max(widths[i], len(cell))
    lines = ["  ".join(h.ljust(widths[i]) for i, h in enumerate(headers)).rstrip()]
    for row in rows:
        lines.append("  ".join(cell.ljust(widths[i]) for i, cell in enumerate(row)).rstrip())
    return lines


def weekly_buckets(events, weeks, today):
    """Newest-first list of per-week aggregates."""
    current_week = week_start(today)
    starts = [current_week - timedelta(weeks=i) for i in range(weeks)]
    by_week = defaultdict(list)
    for fields in events:
        if fields["type"] == TIME_TYPE:
            continue
        by_week[week_start(fields["_date"])].append(fields)

    buckets = []
    for start in starts:
        bucket_events = by_week.get(start, [])
        counts, minutes, _missing = summarize(bucket_events)
        buckets.append(
            {
                "start": start,
                "events": bucket_events,
                "counts": counts,
                "total": len(bucket_events),
                "study_min": sum(minutes.values()),
                "days": len(logged_days(bucket_events)),
            }
        )
    return buckets


def trend_label(buckets, index):
    """Compare a week against the average of the four weeks before it."""
    bucket = buckets[index]
    if bucket["days"] < MIN_LOGGED_DAYS:
        return "low data"
    prior = [b for b in buckets[index + 1: index + 5] if b["days"] >= MIN_LOGGED_DAYS]
    if len(prior) < 2:
        return "n/a"
    avg = sum(b["total"] for b in prior) / len(prior)
    if avg == 0:
        return "n/a"
    pct = (bucket["total"] - avg) / avg * 100
    if abs(pct) < 5:
        return "flat"
    return "%+d%% vs 4wk" % round(pct)


def weekly_report(buckets):
    """Lines for the weekly table: one column per type seen, plus study minutes."""
    totals = Counter()
    for bucket in buckets:
        totals.update(bucket["counts"])
    types = [name for name, _ in totals.most_common()]

    headers = ["week", "days", "events"] + types + ["study_min", "trend"]
    rows = []
    for i, bucket in enumerate(buckets):
        row = [
            bucket["start"].isoformat(),
            str(bucket["days"]),
            str(bucket["total"]),
        ]
        row += [str(bucket["counts"].get(name, 0)) for name in types]
        row.append(str(bucket["study_min"]))
        row.append(trend_label(buckets, i))
        rows.append(row)
    return headers, rows


def difficulty_report(buckets):
    """Weekly leetcode counts by diff::, to catch an easy-only grind."""
    levels = []
    for bucket in buckets:
        for fields in bucket["events"]:
            if fields["type"] != "leetcode":
                continue
            level = fields.get("diff") or "(none)"
            if level not in levels:
                levels.append(level)
    if not levels:
        return None
    order = [lv for lv in ("easy", "medium", "hard") if lv in levels]
    order += [lv for lv in levels if lv not in order]

    headers = ["week"] + order
    rows = []
    for bucket in buckets:
        counts = Counter(
            (f.get("diff") or "(none)") for f in bucket["events"] if f["type"] == "leetcode"
        )
        rows.append([bucket["start"].isoformat()] + [str(counts.get(lv, 0)) for lv in order])
    return headers, rows


def pipeline_report(events):
    """Stage counts across all history, plus conversion between neighbouring stages."""
    counts = Counter()
    for fields in events:
        stage = fields.get("stage")
        if stage:
            counts[stage] += 1
    if not counts:
        return None
    order = [s for s in PIPELINE_STAGES if s in counts]
    order += sorted(s for s in counts if s not in PIPELINE_STAGES)

    rows = []
    for i, stage in enumerate(order):
        conv = ""
        if i > 0 and stage in PIPELINE_STAGES and order[i - 1] in PIPELINE_STAGES:
            prev = counts[order[i - 1]]
            if prev:
                conv = "%d%%" % round(counts[stage] / prev * 100)
        rows.append([stage, str(counts[stage]), conv])
    return ["stage", "count", "from prev"], rows


def streak_lines(events, today, tracked_types=("leetcode", "study")):
    lines = []
    current, longest = streak(logged_days(events), today)
    lines.append("  any event   current %s, longest %s" % (current, longest))
    for name in tracked_types:
        days = {f["_date"] for f in events if f["type"] == name}
        if not days:
            continue
        current, longest = streak(days, today)
        lines.append("  %-11s current %s, longest %s" % (name, current, longest))
    return lines


def print_lines(lines):
    for line in lines:
        print(line)


# ---- generated notes (Stats.md / Dashboard.md) -----------------------------


def stats_markdown():
    return (
        GENERATED_HEADER
        + "\n"
        "# Stats\n"
        "\n"
        "## Event counts (last 30 days)\n"
        "\n"
        "```dataview\n"
        "TABLE length(rows) AS Count\n"
        'FROM "daily"\n'
        "WHERE file.day >= date(today) - dur(29 days)\n"
        "FLATTEN file.tasks AS t\n"
        "WHERE t.completed\n"
        'WHERE t.type != "time"\n'
        "GROUP BY t.type\n"
        "SORT Count DESC\n"
        "```\n"
        "\n"
        "## Study minutes by topic\n"
        "\n"
        "```dataview\n"
        "TABLE sum(rows.t.duration) AS Minutes\n"
        'FROM "daily"\n'
        "WHERE file.day >= date(today) - dur(29 days)\n"
        "FLATTEN file.tasks AS t\n"
        'WHERE t.completed AND t.type = "study"\n'
        "GROUP BY t.topic\n"
        "SORT Minutes DESC\n"
        "```\n"
    )


def bar(value, peak, width=BAR_WIDTH):
    """A proportional ASCII bar. Any non-zero value gets at least one mark, so a
    small week reads as small, never as nothing."""
    if value <= 0 or peak <= 0:
        return ""
    return BAR_CHAR * max(1, int(round(value / peak * width)))


def bar_column(headers, rows, source_index, label="chart"):
    """Append a bar column scaled to the largest value in an existing numeric column."""
    values = []
    for row in rows:
        try:
            values.append(int(row[source_index]))
        except ValueError:
            values.append(0)
    peak = max(values) if values else 0
    return headers + [label], [row + [bar(v, peak)] for row, v in zip(rows, values)]


def type_count_report(type_counts):
    """Event counts per type, largest first, with a bar."""
    if not type_counts:
        return None
    peak = max(type_counts.values())
    rows = [[name, str(n), bar(n, peak)] for name, n in type_counts.most_common()]
    return ["type", "count", "chart"], rows


def study_topic_report(events):
    """Study minutes per topic, largest first, with a bar."""
    _counts, minutes, _missing = summarize(events)
    if not minutes:
        return None
    peak = max(minutes.values())
    rows = [[topic, str(mins), bar(mins, peak)] for topic, mins in minutes.most_common()]
    return ["topic", "minutes", "chart"], rows


def markdown_table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for row in rows:
        out.append("| " + " | ".join(row) + " |")
    return out


def dashboard_markdown(events, buckets, today):
    lines = [GENERATED_HEADER.rstrip("\n"), "", "# Dashboard", "", "Generated %s." % today.isoformat(), ""]

    lines += ["## Weekly", ""]
    headers, rows = weekly_report(buckets)
    # The bar tracks total events (column 2) — the number the trend column judges.
    lines += markdown_table(*bar_column(headers, rows, 2))
    lines.append("")
    lines.append(
        "`days` is days-with-at-least-one-event; a week under %s logged days reads as "
        "insufficient data, not decline." % MIN_LOGGED_DAYS
    )
    lines.append("")

    diff = difficulty_report(buckets)
    if diff:
        lines += ["## Leetcode difficulty mix", ""]
        lines += markdown_table(diff[0], diff[1])
        lines.append("")

    window_start = today - timedelta(days=DASHBOARD_TOPIC_DAYS - 1)
    times = sibling_module("watch").time_report(
        [f for f in events if window_start <= f["_date"] <= today]
    )
    if times:
        lines += ["## Time by category (last %d days)" % DASHBOARD_TOPIC_DAYS, ""]
        lines += markdown_table(*times)
        lines.append("")

    lines += ["## Streaks", ""]
    for line in streak_lines(events, today):
        lines.append("- " + line.strip())
    lines.append("")

    pipeline = pipeline_report(events)
    if pipeline:
        lines += ["## Application pipeline", ""]
        lines += markdown_table(pipeline[0], pipeline[1])
        lines.append("")

    lines += ["## Study minutes by topic (last %d days)" % DASHBOARD_TOPIC_DAYS, ""]
    window_start = today - timedelta(days=DASHBOARD_TOPIC_DAYS - 1)
    topics = study_topic_report(
        [f for f in events if window_start <= f["_date"] <= today]
    )
    if topics:
        lines += markdown_table(*topics)
        lines.append("")
    lines += [
        "```dataview",
        "TABLE sum(rows.t.duration) AS Minutes",
        'FROM "daily"',
        "WHERE file.day >= date(today) - dur(29 days)",
        "FLATTEN file.tasks AS t",
        'WHERE t.completed AND t.type = "study"',
        "GROUP BY t.topic",
        "SORT Minutes DESC",
        "```",
        "",
    ]
    return "\n".join(lines)


def emit_csv(events):
    base = ["date", "type", "when", "detail", "topic", "duration"]
    extra = sorted({k for f in events for k in f if k not in base and not k.startswith("_")})
    writer = csv.writer(sys.stdout, lineterminator="\n")
    writer.writerow(base + extra)
    for fields in events:
        row = [fields["_date"].isoformat()]
        row += [fields.get(name, "") for name in base[1:]]
        row += [fields.get(name, "") for name in extra]
        writer.writerow(row)


# ---- stats -----------------------------------------------------------------


def cmd_stats(args):
    if args.days not in ("7", "30"):
        die("days must be 7 or 30")
    if args.weeks is not None and args.weeks < 1:
        die("--weeks must be at least 1")

    vault = vault_path()
    today = working_date()

    if args.csv:
        events, _unparseable = load_events(vault)
        emit_csv(events)
        return

    weeks = args.weeks if args.weeks is not None else 8
    if args.weeks is not None:
        report_start = week_start(today) - timedelta(weeks=weeks - 1)
    else:
        report_start = today - timedelta(days=int(args.days) - 1)

    all_events, unparseable = load_events(vault, warn_start=report_start)

    if args.pipeline:
        report = pipeline_report(all_events)
        if report is None:
            print("no events with a stage:: field")
            return
        print_lines(render_table(report[0], report[1]))
        return

    week_window = week_start(today) - timedelta(weeks=weeks - 1)
    buckets = weekly_buckets(
        [f for f in all_events if f["_date"] >= week_window], weeks, today
    )

    if args.weeks is not None:
        headers, rows = weekly_report(buckets)
        # Same bars as Dashboard.md: one set of numbers should look like itself
        # wherever you read it.
        print_lines(render_table(*bar_column(headers, rows, 2)))
        diff = difficulty_report(buckets)
        if diff:
            print("")
            print("leetcode by difficulty")
            print_lines(render_table(diff[0], diff[1]))
        times = sibling_module("watch").time_weekly_report(
            [f for f in all_events if f["_date"] >= week_window], weeks, today
        )
        if times:
            print("")
            print("time by category")
            print_lines(render_table(*times))
    else:
        n = int(args.days)
        window = [f for f in all_events if report_start <= f["_date"] <= today]
        type_counts, _study_minutes, missing_duration = summarize(window)

        print("events (%s days)" % n)
        counts = type_count_report(type_counts)
        if counts:
            print_lines("  " + line for line in render_table(*counts))
        else:
            print("  (none)")

        print("study minutes")
        topics = study_topic_report(window)
        if topics:
            print_lines("  " + line for line in render_table(*topics))
        else:
            print("  (none)")
        if missing_duration:
            print("  sessions without duration: %s" % missing_duration)

        times = sibling_module("watch").time_report(window)
        if times:
            print("time by category")
            print_lines("  " + line for line in render_table(*times))

        days = len(logged_days(window))
        print("logging: %s of %s days had an event" % (days, n))

    print("")
    print("streaks")
    print_lines(streak_lines(all_events, today))

    if unparseable:
        print("skipped %s unparseable lines" % unparseable, file=sys.stderr)


# ---- dash ------------------------------------------------------------------
#
# The only command that overwrites files in the vault root. It is deliberately not
# folded into `stats`: "show me numbers" must never rewrite notes as a side effect.


def write_generated_notes(vault, weeks=DASH_WEEKS):
    """Overwrite Stats.md and Dashboard.md. The only writes outside daily notes."""
    today = working_date()
    events, _unparseable = load_events(vault)
    window = week_start(today) - timedelta(weeks=weeks - 1)
    buckets = weekly_buckets([f for f in events if f["_date"] >= window], weeks, today)

    for name, body in (
        ("Stats.md", stats_markdown()),
        ("Dashboard.md", dashboard_markdown(events, buckets, today)),
    ):
        path = os.path.join(vault, name)
        write_text(path, body)
        print("wrote %s" % path)


def cmd_dash(args):
    if args.weeks < 1:
        die("--weeks must be at least 1")
    write_generated_notes(vault_path(), args.weeks)


def existing_ids(content):
    """Return durable dedupe IDs from completed tasks in the Log section."""
    ids = set()
    for raw in log_section(content).splitlines():
        m = COMPLETED_TASK_RE.match(raw.rstrip("\r"))
        if not m:
            continue
        value = parse_fields(m.group(1)).get("id")
        if value:
            ids.add(value)
    return ids


def append_commit_lines(vault, by_day, dry_run):
    """Append the lines whose id the day's note does not already have. Returns (added, skipped)."""
    added = skipped = 0
    for day in sorted(by_day):
        path = daily_path(vault, day)
        with locked_note(path):
            content = read_text(path) if os.path.isfile(path) else None
            seen = existing_ids(content) if content is not None else set()
            fresh = []
            for _when, ident, line in sorted(by_day[day]):
                if ident in seen:
                    skipped += 1
                    continue
                seen.add(ident)
                fresh.append(line)
            if not fresh:
                continue
            added += len(fresh)
            if dry_run:
                print("%s  +%d" % (day.isoformat(), len(fresh)))
                for line in fresh:
                    print("  %s" % line)
                continue
            os.makedirs(os.path.dirname(path), exist_ok=True)
            content = content if content is not None else new_daily_content(vault, day)
            for line in fresh:
                content = insert_under_log(content, line)
            write_text(path, content)
    return added, skipped


# ---- CLI -------------------------------------------------------------------


def sibling_module(name):
    """Import a module next to this file. Commands big enough to need their own file
    are loaded on use, so the CLI still starts with nothing but the stdlib parsed."""
    here = os.path.dirname(os.path.abspath(__file__))
    if here not in sys.path:
        sys.path.insert(0, here)
    try:
        return __import__(name)
    except ImportError as exc:
        die("could not load %s.py: %s" % (name, exc))


def cmd_sync(args):
    """Import local Git commits. Git-specific code lives in sync.py."""
    sibling_module("sync").cmd_sync(args)


def cmd_gui(_args):
    """Open the quick-add window. The window itself lives in quickadd.py: this file
    stays the CLI, and tkinter is imported only if you ask for it."""
    sys.exit(sibling_module("quickadd").main())


def cmd_suggest(args):
    """Propose events from local evidence. The reader lives in suggest.py."""
    sibling_module("suggest").cmd_suggest(args)


def cmd_recap(args):
    """Run the short evidence/confirmation/learning daily review."""
    sibling_module("recap").cmd_recap(args)


def cmd_review(args):
    """Write reviews/YYYY-Www.md. The note's shape lives in review.py; its numbers
    come back through this file's report functions, so the two cannot disagree."""
    sibling_module("review").cmd_review(args)


def cmd_label(args):
    """Propose one topic per recent note. Lives in label.py: it is the only command
    that shells out to a model, and nothing else here should have to import it."""
    sibling_module("label").cmd_label(args)


def cmd_setup(args):
    """Create a vault and print the profile block. Lives in bootstrap.py."""
    sibling_module("bootstrap").cmd_setup(args)


def cmd_watch(args):
    """Measure foreground time into `time` events. Lives in watch.py: the only
    code that reads window titles, and they never leave its memory."""
    sibling_module("watch").cmd_watch(args)


def cmd_complete(args):
    """Words the shell may offer after `t`. Derived from the parser, never a
    second list to keep in sync: a new flag is completable the day it exists."""
    parser = build_parser()
    sub = parser.tracker_subparsers.get(args.word or "")
    if sub is None:
        words = list(SUBCOMMANDS) + list(VALID_TYPES)
    else:
        words = [opt for action in sub._actions for opt in action.option_strings]
    for word in sorted(set(words)):
        print(word)


# Bare `t`: the four actions worth remembering, in the order you reach for them.
CHEATSHEET = (
    ("recap", "t recap", "collect today's evidence"),
    ("log", "t <type> [detail...]", "add what recap could not see"),
    ("read", "t week", "see counts, time and streaks"),
    ("review", "t review", "choose one change for next week"),
)


def print_cheatsheet():
    width = max(len(label) for label, _, _ in CHEATSHEET)
    for label, usage, note in CHEATSHEET:
        print("  %s  %-31s %s" % (label.ljust(width), usage, note))
    print("")
    print(textwrap.fill(
        "types: " + ", ".join(VALID_TYPES), width=78, subsequent_indent="       "
    ))
    print("`t --help` for every flag.")


def cmd_overview():
    """Bare `t`: what today looks like, then how to add to it."""
    raw = os.environ.get("VAULT_PATH")
    if raw and os.path.isdir(raw):
        cmd_today(argparse.Namespace(date=None))
    else:
        # Never fatal: the cheatsheet is exactly what someone with no vault needs,
        # and setup is the one command that gets them one.
        print("VAULT_PATH is not set to an existing directory; nothing to show yet.")
        print('Start with:  t setup "D:\\path\\to\\vault"')
    print("")
    print_cheatsheet()


def build_parser():
    parser = argparse.ArgumentParser(prog="tracker.py")
    sub = parser.add_subparsers(dest="cmd", required=True)

    track_p = sub.add_parser("track", help="Append an event to the daily note")
    track_p.add_argument("event_type", metavar="type")
    track_p.add_argument("detail", nargs="*")
    track_p.add_argument("--date", metavar="D", help="Override working date (YYYY-MM-DD)")
    track_p.add_argument("--topic", metavar="T")
    track_p.add_argument("--duration", metavar="MIN", type=int)
    track_p.add_argument(
        "--x",
        dest="extra",
        action="append",
        metavar="K=V",
        help="Extra inline field; repeatable",
    )
    track_p.set_defaults(func=cmd_track)

    today_p = sub.add_parser("today", help="Print today's log lines")
    today_p.add_argument("--date", metavar="D", help="Show another date (YYYY-MM-DD)")
    today_p.set_defaults(func=cmd_today)

    undo_p = sub.add_parser("undo", help="Remove the last line this tool appended")
    undo_p.add_argument("--date", metavar="D", help="Undo on another date (YYYY-MM-DD)")
    undo_p.add_argument("--yes", action="store_true", help="Skip the confirmation prompt")
    undo_p.set_defaults(func=cmd_undo)

    stats_p = sub.add_parser("stats", help="Print event counts, streaks and trends")
    stats_p.add_argument("days", nargs="?", default="7")
    stats_p.add_argument("--weeks", metavar="N", type=int, help="Weekly buckets over N weeks")
    stats_p.add_argument("--pipeline", action="store_true", help="Application funnel by stage::")
    stats_p.add_argument("--csv", action="store_true", help="Dump all events as CSV to stdout")
    stats_p.set_defaults(func=cmd_stats)

    for name, days, help_text in STATS_ALIASES:
        alias_p = sub.add_parser(name, help="%s: same as t stats %s" % (help_text, days))
        alias_p.set_defaults(
            func=cmd_stats, days=days, weeks=None, pipeline=False, csv=False
        )

    dash_p = sub.add_parser("dash", help="Write Stats.md and Dashboard.md into the vault")
    dash_p.add_argument(
        "--weeks",
        metavar="N",
        type=int,
        default=DASH_WEEKS,
        help="Weeks in the weekly table",
    )
    dash_p.set_defaults(func=cmd_dash)

    sync_p = sub.add_parser("sync", help="Import git commits into the daily notes")
    sync_p.add_argument(
        "--repo", action="append", metavar="PATH", help="Repository to scan; repeatable"
    )
    sync_p.add_argument(
        "--root",
        action="append",
        metavar="DIR",
        help="Scan DIR and its immediate subdirectories for repos; repeatable",
    )
    sync_p.add_argument("--days", metavar="N", type=int, default=14, help="Look back N days")
    sync_p.add_argument(
        "--author", metavar="EMAIL", help="Default: each repo's own git user.email"
    )
    sync_p.add_argument("--dry-run", action="store_true", help="Show what would be added")
    sync_p.add_argument(
        "--no-dash",
        action="store_true",
        help="Do not refresh Stats.md and Dashboard.md afterwards",
    )
    sync_p.set_defaults(func=cmd_sync)

    review_p = sub.add_parser("review", help="Write reviews/YYYY-Www.md for last week")
    review_p.add_argument("--week", metavar="D", help="Any date inside the week to review")
    review_p.add_argument(
        "--print", dest="print_only", action="store_true", help="Print instead of writing"
    )
    review_p.set_defaults(func=cmd_review)

    label_p = sub.add_parser("label", help="Suggest topic labels for recent notes")
    label_p.set_defaults(func=cmd_label)

    suggest_p = sub.add_parser(
        "suggest", help="Propose events from browser history; writes only what you pick"
    )
    suggest_p.add_argument("--days", metavar="N", type=int, default=3, help="Look back N days")
    suggest_p.add_argument("--yes", action="store_true", help="Apply every proposal")
    suggest_p.add_argument("--dry-run", action="store_true", help="Show proposals, write nothing")
    suggest_p.set_defaults(func=cmd_suggest)

    recap_p = sub.add_parser("recap", help="Import facts, confirm suggestions, summarize today")
    recap_p.add_argument("--date", metavar="D", help="Recap another working day")
    recap_p.add_argument("--dry-run", action="store_true", help="Discover and print; write nothing")
    recap_p.set_defaults(func=cmd_recap)

    setup_p = sub.add_parser("setup", help="Create a vault and print the profile block")
    setup_p.add_argument("path", nargs="?", help="Where the vault goes (default: $VAULT_PATH)")
    setup_p.add_argument(
        "--profile", action="store_true", help="Append the block to your PowerShell profile"
    )
    setup_p.add_argument(
        "--watch-task", action="store_true", help="Register `t watch` to start at login"
    )
    setup_p.add_argument(
        "--persist-env",
        action="store_true",
        help="Save VAULT_PATH in your Windows user environment",
    )
    setup_p.add_argument(
        "--remove", action="store_true", help="With --watch-task: unregister it"
    )
    setup_p.set_defaults(func=cmd_setup)

    gui_p = sub.add_parser("gui", help="Open the quick-add window")
    gui_p.set_defaults(func=cmd_gui)

    watch_p = sub.add_parser("watch", help="Watch the foreground window; log time by category")
    watch_p.add_argument("--interval", metavar="SEC", type=int, default=5, help="Sample every SEC seconds")
    watch_p.add_argument("--idle", metavar="SEC", type=int, default=180, help="Stop the clock after SEC seconds without input")
    watch_p.add_argument("--status", action="store_true", help="Report whether a watcher is running")
    watch_p.add_argument("--rules", action="store_true", help="Print effective classification rules")
    watch_p.add_argument("--add-rule", nargs=2, metavar=("PATTERN", "CATEGORY"), help="Append one custom rule")
    watch_p.set_defaults(func=cmd_watch)

    complete_p = sub.add_parser("complete", help="List completion words for the shell")
    complete_p.add_argument("word", nargs="?", help="Subcommand whose flags to list")
    complete_p.set_defaults(func=cmd_complete)

    # What the shell completer reads; kept here so there is one source of truth.
    parser.tracker_subparsers = sub.choices
    return parser


def harden_output_encoding(streams):
    """Never die while printing someone else's text.

    Generated text is kept ASCII on purpose, but commit subjects and page titles are
    not ours: an em-dash reaching a cp1252 console raises UnicodeEncodeError and takes
    the command down. Degrade the character, not the run.
    """
    for stream in streams:
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is None:
            continue
        try:
            reconfigure(errors="replace")
        except (ValueError, OSError):
            pass


def main(argv=None):
    harden_output_encoding((sys.stdout, sys.stderr))
    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv:
        # A bare `t` should teach, not scold: argparse's "required" usage blob helps
        # nobody, and "what did I log today" is the thing you actually wanted.
        cmd_overview()
        return
    if not argv[0].startswith("-"):
        # `t commit "msg"` means `track commit "msg"`; subcommand names still win.
        if argv[0] == TIME_TYPE:
            # Measured attention cannot be typed: a hand-written hour is a guess.
            die("time events are written by `t watch`, never by hand.")
        if argv[0] in VALID_TYPES:
            argv.insert(0, "track")
        elif argv[0] not in SUBCOMMANDS:
            die(
                "unknown command or type %s.%s\ncommands: %s\ntypes: %s"
                % (
                    argv[0],
                    suggest(argv[0], SUBCOMMANDS + VALID_TYPES),
                    ", ".join(SUBCOMMANDS),
                    ", ".join(VALID_TYPES),
                )
            )
    parser = build_parser()
    if argv[0] == "track":
        # argparse stops collecting `nargs="*"` after an option; keep plain words.
        args, trailing = parser.parse_known_args(argv)
        if any(word.startswith("-") for word in trailing):
            parser.error("unrecognized arguments: %s" % " ".join(trailing))
        args.detail.extend(trailing)
    else:
        args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
